/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartList: typeof import('./../components/List/CartList/index.vue')['default']
    CopyRight: typeof import('./../components/CopyRight.vue')['default']
    IconSection: typeof import('./../components/TopBanner/IconSection/index.vue')['default']
    Logo: typeof import('./../components/TopBanner/Logo.vue')['default']
    NavigationDialog: typeof import('./../components/TopBanner/IconSection/UserSection/NavigationDialog.vue')['default']
    NotificationDialog: typeof import('./../components/TopBanner/IconSection/UserSection/NotificationDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/Search/SearchBar.vue')['default']
    SearchCard: typeof import('./../components/Search/SearchCard.vue')['default']
    SearchDialog: typeof import('./../components/Dialog/SearchDialog.vue')['default']
    SearchGallery: typeof import('./../components/Search/SearchGallery.vue')['default']
    ThemeBackground: typeof import('./../components/ThemeBackground/index.vue')['default']
    TopBanner: typeof import('./../components/TopBanner/index.vue')['default']
    UserSection: typeof import('./../components/TopBanner/IconSection/UserSection/index.vue')['default']
    ZoomPhoto: typeof import('./../components/ZoomPhoto.vue')['default']
  }
}
